// <auto-generated />
namespace WindowsEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CambiodenombreCategoria_IdaIdCategoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambiodenombreCategoria_IdaIdCategoria));
        
        string IMigrationMetadata.Id
        {
            get { return "202211081803027_ Cambio de nombre Categoria_Id a IdCategoria "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
